spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookish
    driver-class-title: com.mysql.jdbc.Driver
    username: bookish-admin
    password: password

server:
  port: 9999

---

spring:
  profiles: integration

  datasource:
    url: jdbc:mysql://localhost:3306/bookish_test
    driver-class-title: com.mysql.jdbc.Driver
    username: bookish-admin
    password: password
